name: Hangugeoreoul Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.13.0
        
    - name: Install dependencies
      run: npm i
      
    - name: Lint with EsLint
      run: npx eslint .
